Create Database InscripcionesBrDb
GO

USE [InscripcionesBrDb]
GO


CREATE TABLE [dbo].[Persona] (
    [Id]              INT           IDENTITY (1, 1) NOT NULL,
    [Rut]             NVARCHAR (13) NULL,
    [Nombre]          NVARCHAR (50) NOT NULL,
    [FechaNacimiento] DATE          NOT NULL,
    [Email]           NCHAR (50)    NOT NULL,
    [Dirección]       NCHAR (50)    NULL,
    CONSTRAINT [PK_Persona] PRIMARY KEY CLUSTERED ([Id] ASC)
);
GO


CREATE TABLE [dbo].[RealStateForm] (
    [attentionNumber]   INT           IDENTITY (1, 1) NOT NULL,
    [natureOfTheDeed]   VARCHAR (MAX) NOT NULL,
    [commune]           VARCHAR (MAX) NOT NULL,
    [block]             VARCHAR (MAX) NOT NULL,
    [property]          VARCHAR (MAX) NOT NULL,
    [sheets]            INT           NOT NULL,
    [inscriptionDate]   DATE          NOT NULL,
    [inscriptionNumber] INT           NOT NULL,
    PRIMARY KEY CLUSTERED ([attentionNumber] ASC)
);
GO



CREATE TABLE [dbo].[MultiOwner] (
    [Id]                  INT           IDENTITY (1, 1) NOT NULL,
    [rut]                 NCHAR (13)    NULL,
    [ownershipPercentage] FLOAT (53)    NULL,
    [commune]             VARCHAR (MAX) NOT NULL,
    [block]               VARCHAR (MAX) NOT NULL,
    [property]            VARCHAR (MAX) NOT NULL,
    [sheets]              INT           NOT NULL,
    [inscriptionDate]     DATE          NOT NULL,
    [inscriptionNumber]   INT           NOT NULL,
    [validityYearBegin]             INT           NULL,
    [validityYearFinish]             INT           NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC)
    );
GO

CREATE TABLE [dbo].[People] (
    [Id]                  INT        IDENTITY (1, 1) NOT NULL,
    [rut]                 NCHAR (13) NULL,
    [ownershipPercentage] FLOAT (53) NULL,
    [uncreditedOwnership] BIT        NULL,
    [formsId]             INT        NULL,
    [seller]              BIT        NULL,
    [heir]                BIT        NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_People_(ToTableColumn)] FOREIGN KEY ([formsId]) REFERENCES [dbo].[RealStateForm] ([attentionNumber])
);
GO



USE [InscripcionesBrDb]
GO
SET IDENTITY_INSERT [dbo].[Persona] ON 
GO
INSERT [dbo].[Persona] ([Id], [Rut], [Nombre], [FechaNacimiento], [Email], [Dirección]) VALUES (1, N'10915348-6', N'Mario Abellan', CAST(N'1982-01-15' AS Date), N'marioabellan@gmail.com', N'Galvarino Gallardo 1534')
GO
SET IDENTITY_INSERT [dbo].[Persona] OFF
GO


CREATE TABLE Communes (
  [Id]              INT           IDENTITY (1, 1) NOT NULL PRIMARY KEY,
  Name VARCHAR(50) NOT NULL,
);

INSERT INTO Communes (Name) 
VALUES 
('Algarrobo'),
('Alto Biobío'),
('Alto del Carmen'),
('Ancud'),
('Andacollo'),
('Angol'),
('Antártica'),
('Antofagasta'),
('Antuco'),
('Arauco'),
('Arica'),
('Arica y Parinacota'),
('Aysén'),
('Buin'),
('Bulnes'),
('Cabildo'),
('Cabo de Hornos'),
('Cabrero'),
('Calama'),
('Caldera'),
('Calera de Tango'),
('Calle Larga'),
('Canela'),
('Carahue'),
('Cartagena'),
('Casablanca'),
('Castro'),
('Catemu'),
('Cauquenes'),
('Cañete'),
('Cerro Navia'),
('Chaitén'),
('Chañaral'),
('Chépica'),
('Chillán'),
('Chillán Viejo'),
('Chimbarongo'),
('Cholchol'),
('Cisnes'),
('Cobquecura'),
('Cochamó'),
('Cochrane'),
('Codegua'),
('Coelemu'),
('Coinco'),
('Colbún'),
('Colchane'),
('Colina'),
('Collipulli'),
('Coltauco'),
('Combarbalá'),
('Concepción'),
('Concón'),
('Constitución'),
('Contulmo'),
('Copiapó'),
('Coquimbo'),
('Coronel'),
('Corral'),
('Coyhaique'),
('Cunco'),
('Curacautín'),
('Curacaví'),
('Curaco de Vélez'),
('Curanilahue'),
('Curarrehue'),
('Curepto'),
('Curicó'),
('Dalcahue'),
('Diego de Almagro'),
('Doñihue'),
('El Bosque'),
('El Carmen'),
('El Monte'),
('El Quisco'),
('El Tabo'),
('Empedrado'),
('Ercilla'),
('Estación Central'),
('Florida'),
('Freire'),
('Freirina'),
('Fresia'),
('Frutillar'),
('Futaleufú'),
('Futrono'),
('Galvarino'),
('General Lagos'),
('Gorbea'),
('Graneros'),
('Guaitecas'),
('Hijuelas'),
('Hualaihué'),
('Hualañé'),
('Hualpén'),
('Hualqui'),
('Huara'),
('Huasco'),
('Huechuraba'),
('Illapel'),
('Independencia'),
('Iquique'),
('Isla de Maipo'),
('Isla de Pascua'),
('Juan Fernández'),
('La Calera'),
('La Cisterna'),
('La Cruz'),
('La Estrella'),
('La Florida'),
('La Granja'),
('La Higuera'),
('La Ligua'),
('La Pintana'),
('La Reina'),
('La Serena'),
('La Unión'),
('Lago Ranco'),
('Lago Verde'),
('Laguna Blanca'),
('Laja'),
('Lampa'),
('Lampazos'),
('Las Cabras'),
('Las Condes'),
('Lautaro'),
('Lebu'),
('Licantén'),
('Limache'),
('Linares'),
('Litueche'),
('Llanquihue'),
('Lo Barnechea'),
('Lo Espejo'),
('Lo Prado'),
('Lolol'),
('Loncoche'),
('Longaví'),
('Lonquimay'),
('Los Alamos'),
('Los Andes'),
('Los Ángeles'),
('Los Lagos'),
('Los Muermos'),
('Los Sauces'),
('Los Vilos'),
('Lota'),
('Lumaco'),
('Machalí'),
('Macul'),
('Máfil'),
('Maipú'),
('Malloa'),
('Marchihue'),
('María Elena'),
('María Pinto'),
('Mariquina'),
('Maule'),
('Mejillones'),
('Melipeuco'),
('Melipilla'),
('Molina'),
('Monte Patria'),
('Mostazal'),
('Mulchén'),
('Nacimiento'),
('Nancagua'),
('Natales'),
('Navidad'),
('Negrete'),
('Ninhue'),
('Nogales'),
('Nueva Imperial'),
('Ñiquén'),
('Ñuñoa'),
('OHiggins'),
('Olivar'),
('Olmué'),
('Osorno'),
('Ovalle'),
('Padre Hurtado'),
('Padre Las Casas'),
('Paihuano'),
('Palena'),
('Palmilla'),
('Panguipulli'),
('Panquehue'),
('Papudo'),
('Paredones'),
('Parral'),
('Pedro Aguirre Cerda'),
('Pelarco'),
('Pelluhue'),
('Pemuco'),
('Pencahue'),
('Penco'),
('Peñaflor'),
('Peñalolén'),
('Peralillo'),
('Perquenco'),
('Petorca'),
('Peumo'),
('Pica'),
('Pichidegua'),
('Pichilemu'),
('Pinto'),
('Pirque'),
('Pitrufquén'),
('Placilla'),
('Portezuelo'),
('Porvenir'),
('Pozo Almonte'),
('Primavera'),
('Providencia'),
('Puchuncaví'),
('Pucón'),
('Pudahuel'),
('Puente Alto'),
('Puerto Montt'),
('Puerto Octay'),
('Puerto Varas'),
('Pumanque'),
('Punitaqui'),
('Punta Arenas'),
('Puqueldón'),
('Purén'),
('Purranque'),
('Puyehue'),
('Queilén'),
('Quellón'),
('Quemchi'),
('Quilaco'),
('Quilicura'),
('Quilleco'),
('Quillón'),
('Quillota'),
('Quinta de Tilcoco'),
('Quinta Normal'),
('Quintero'),
('Quirihue'),
('Rancagua'),
('Ránquil'),
('Rauco'),
('Recoleta'),
('Renaico'),
('Renca'),
('Rengo'),
('Requínoa'),
('Retiro'),
('Rinconada'),
('Río Bueno'),
('Río Claro'),
('Río Hurtado'),
('Río Ibáñez'),
('Río Negro'),
('Río Verde'),
('Romeral'),
('Saavedra'),
('Sagrada Familia'),
('Salamanca'),
('San Antonio'),
('San Bernardo'),
('San Carlos'),
('San Clemente'),
('San Esteban'),
('San Fabián'),
('San Felipe'),
('San Fernando'),
('San Gregorio'),
('San Ignacio'),
('San Javier'),
('San Joaquín'),
('San José de Maipo'),
('San Juan de la Costa'),
('San Miguel'),
('San Nicolás'),
('San Pablo'),
('San Pedro'),
('San Pedro de Atacama'),
('San Pedro de la Paz'),
('San Rafael'),
('San Ramón'),
('San Rosendo'),
('San Vicente de Tagua Tagua'),
('Santa Bárbara'),
('Santa Cruz'),
('Santa Juana'),
('Santa María'),
('Santiago'),
('Santo Domingo'),
('Sierra Gorda'),
('Talagante'),
('Talca'),
('Talcahuano'),
('Taltal'),
('Temuco'),
('Teno'),
('Teodoro Schmidt'),
('Tierra Amarilla'),
('Til Til'),
('Timaukel'),
('Tirúa'),
('Tocopilla'),
('Toltén'),
('Tomé'),
('Torres del Paine'),
('Tortel'),
('Traiguén'),
('Treguaco'),
('Tucapel'),
('Valdivia'),
('Vallenar'),
('Valparaíso'),
('Vichuquén'),
('Victoria'),
('Vicuña'),
('Vilcún'),
('Villa Alegre'),
('Villa Alemana'),
('Villarrica'),
('Viña del Mar'),
('Vitacura'),
('Yerbas Buenas'),
('Yumbel'),
('Yungay');